### ISSUE TITLE
Can not "make" in the latest version of kaldi

### ISSUE THREAD

**Issue by xanxus1204** [dansoutner/kaldi2htk#1]
I tried to make with latest version of kaldi.
But I got warning message below.

make -C /home/user/tools/kaldi/src//thread kaldi-thread.a
make[1]: *** /home/user/tools/kaldi/src//thread: そのようなファイルやディレクトリはありません.  中止.
/home/user/tools/kaldi/src//makefiles/default_rules.mk:61: recipe for target '/home/user/tools/kaldi/src//thread/kaldi-thread.a' failed
make: *** [/home/user/tools/kaldi/src//thread/kaldi-thread.a] Error 2

**Comment by dansoutner** [comment]
Removed link to kaldi-thread.a, should be fixed now.
